# Generated by Django 4.1 on 2022-09-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=40, verbose_name='userId')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('session', models.IntegerField(blank=True, null=True)),
                ('startDate', models.TextField(blank=True, null=True)),
                ('endDate', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
